name = "HighOrderMeshes"
uuid = "f18c5c57-76fa-4ade-9d1a-7f3a1f8a4b32"
authors = ["Per-Olof Persson <persson@berkeley.edu>"]
version = "0.2.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a" 
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TriplotRecipes = "808ab39a-a642-4abf-81ff-4cb34ebbffa3"

[extensions]
HighOrderMeshesMakieExt = "Makie" 
HighOrderMeshesPlotsExt = ["Plots", "TriplotRecipes"]

[compat]
julia = "1.10"
LinearAlgebra = "1.10"
SparseArrays = "1.10"
HDF5 = "0.17, 1"
StaticArrays = "1"
Plots = "1"
Makie = "0.24"
TriplotRecipes = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
