name = "HighOrderMeshes"
uuid = "f18c5c57-76fa-4ade-9d1a-7f3a1f8a4b32"
version = "0.2.0"
authors = ["Per-Olof Persson <persson@berkeley.edu>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TriplotRecipes = "808ab39a-a642-4abf-81ff-4cb34ebbffa3"

[extensions]
HighOrderMeshesMakieExt = "Makie"
HighOrderMeshesPlotsExt = ["Plots", "TriplotRecipes"]

[compat]
CairoMakie = "0.15"
LinearAlgebra = "1.10"
Makie = "0.24"
Plots = "1"
Serialization = "1.11.0"
SparseArrays = "1.10"
StaticArrays = "1"
TriplotRecipes = "0.1"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
